image: hashicorp/terraform:1.6.3

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  BUCKET_TF_STATE: $BUCKET_TF_STATE
  AWS_REGION: "us-east-2"
  EKS_CLUSTER: "vprofile-eks"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .terraform

stages:
  - validate
  - plan
  - apply
  - configure-k8s

before_script:
  - terraform --version
  - terraform init -backend-config="bucket=$BUCKET_TF_STATE"

terraform-validate:
  stage: validate
  script:
    - terraform fmt -check
    - terraform validate

terraform-plan:
  stage: plan
  script:
    - terraform plan -no-color -input=false
  artifacts:
    paths:
      - planfile

terraform-apply:
  stage: apply
  script:
    - terraform apply -auto-approve -input=false planfile
  environment:
    name: production
  only:
    refs:
      - main
    changes:
      - terraform/*

configure-aws:
  stage: configure-k8s
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION
    - aws eks update-kubeconfig --name $EKS_CLUSTER
  dependencies:
    - terraform-apply

install-ingress:
  stage: configure-k8s
  script:
    - kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.3/deploy/static/provider/aws/deploy.yaml
  dependencies:
    - configure-aws